import type { Metadata } from "next";
import { Lalezar } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const lalezar = Lalezar({ 
  weight: ["400"],
  subsets: ["arabic"],
  display: "swap",

});

export const metadata: Metadata = {
  title: "Solo Travel | Travel And Donate With Us",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={lalezar.className}>
        <Navbar />
        <main className="relative rtl">
           {children}
          </main>
        <Footer />
      </body>
    </html>
  );
}
